---
namespace: frc7540
name: frc
version: 1.1.0
readme: README.md

authors:
- Shane Alvarez <shane.alv@gmail.com>

description: A few roles for managing WPILib installations

license:
  - MIT

tags:
  - wpilib
  - first
  - frc

repository: http://github.com/frc7540/ansible-collection-frc
issues: http://github.com/frc7540/ansible-collection-frc/issues

dependencies:
  community.general: "*"
build_ignore:
  - .pytest_cache
  - .venv
