---
# defaults file for java-workstation
wpilib_version_major: "2022"
wpilib_version_minor: "4"
wpilib_version_patch: "1"
wpilib_version: "{{ wpilib_version_major }}.{{ wpilib_version_minor }}.{{ wpilib_version_patch }}"

wpilib_base: "WPILib_Linux-{{ wpilib_version }}"
wpilib_release_archive: "{{ wpilib_base }}.tar.gz"
wpilib_artifacts_archive: "{{ wpilib_base }}-artifacts.tar.gz"

wpilib_release_url: "https://github.com/wpilibsuite/allwpilib/releases/download/v{{ wpilib_version }}"

wpilib_installer_root: /usr/local/wpilib

wpilib_users: [ "shanealvarez" ]