- name: install wpilib for each user
  become: true
  become_user: "{{ user }}"
  block:
    - name: create wpilib directory
      file:
        path: "/home/{{ user }}/wpilib/{{ wpilib_release_version | split('.') | first }}"
        state: directory
        recurse: true
        owner: "{{ user }}"
        group: "{{ user }}"
      register: wpilib_home

    - name: install wpilib
      ansible.builtin.unarchive:
        src: "{{ wpilib_install_root }}/{{ wpilib_artifacts_archive }}"
        dest: "{{ wpilib_home.path }}"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: true
        owner: "{{ user }}"
        group: "{{ user }}"
      loop:
        - "{{ wpilib_home.path }}/vscode/data/extensions"
        - "{{ wpilib_home.path }}/vscode/data/user-data/User"
        - "/home/{{ user }}/.local/share/applications"
        - "/home/{{ user }}/Desktop"

    - name: install wpilib extensions
      wpilib_vscode_userconf:
        path: "{{ wpilib_home.path }}"

    - name: render frc vscode config files and shortcuts
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"
      loop:
        - src: settings.json.j2
          dest: "{{ wpilib_home.path }}/vscode/data/user-data/User/settings.json"
        - src: frccode.desktop.j2
          dest: "/home/{{ user }}/.local/share/applications/frccode.desktop"

    - name: create desktop shortcut link
      ansible.builtin.file:
        src: "/home/{{ user }}/.local/share/applications/frccode.desktop"
        path: "/home/{{ user }}/Desktop/frccode.desktop"
        state: link
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0775"
      register: desktop_shortcut_home
