---
# tasks file for java-workstation
- name: install role dependencies
  ansible.builtin.package:
    name:
      - gzip
      - python3
      - tar
    state: present
    use: apt
  become: true

- name: install vscode
  include_role:
    name: gantsign.visual-studio-code
  when: ansible_distribution != 'Pop!_OS'

- name: install vscode (Pop! OS)
  ansible.builtin.package:
    name:
      - code
    use: apt
  when: ansible_distribution == 'Pop!_OS'
  become: true

- name: install dev tools
  ansible.builtin.package:
    name:
      - git
      - neovim
      - tree
  become: true

- name: create wpilib global install root
  ansible.builtin.file:
    dest: "{{ wpilib_installer_root }}"
    state: directory
    recurse: true
  become: true

- name: download wpilib release
  ansible.builtin.get_url:
    url: "{{ wpilib_release_url }}/{{ wpilib_release_archive }}"
    dest: "{{ wpilib_installer_root }}/{{ wpilib_release_archive }}"
    checksum: "{{ wpilib_release_hash }}"
  become: true

- name: unpack release
  ansible.builtin.unarchive:
    src: "{{ wpilib_installer_root }}/{{ wpilib_release_archive }}"
    dest: "{{ wpilib_installer_root }}"
    include: "{{ wpilib_base }}/{{ wpilib_artifacts_archive }}"
    creates:
      "{{ wpilib_installer_root }}/{{ wpilib_base }}/{{ wpilib_artifacts_archive
      }}"
    remote_src: true
  become: true

- name: install wpilib for each user
  include_tasks: user-install.yml
  loop: "{{ wpilib_users }}"
  loop_control:
    loop_var: user
