---
- name: Ensure required packages installed
  ansible.builtin.apt:
    name:
      - python3-apt
      - xdg-utils
  become: true

- name: Get installed packages
  ansible.builtin.package_facts:
    manager: "apt"

- name: Install balena etcher
  ansible.builtin.apt:
    deb: "{{ balena_etcher_url }}"
  become: true
  when: "'balena-etcher' not in ansible_facts.packages or balena_etcher_version not in ansible_facts.packages['balena-etcher'][0]['version']"

# Fixes GRIP install for ubuntu-jammy container
- name: Make sure desktop-directories exists
  ansible.builtin.file:
    path: /usr/share/desktop-directories
    state: directory
    owner: root
    group: root
  become: true

- name: Install GRIP
  ansible.builtin.apt:
    deb: "{{ grip_url }}"
  become: true
  when: "'grip' not in ansible_facts.packages or grip_version not in ansible_facts.packages['grip'][0]['version']"
