---
- name: Converge
  hosts: all
  vars:
    wpilib_users:
      - vagrant
  pre_tasks:
    - name: Create user
      ansible.builtin.user:
        name: vagrant
        state: present
  roles:
    - role: frc7540.frc.wpilib
