---
- name: Converge
  hosts: all
  vars:
    wpilib_users:
      - vagrant
  pre_tasks:
    - name: create user
      ansible.builtin.user:
        name: vagrant
        state: present
  roles:
    - role: ansible-role-wpilib
