---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml

lint: |
  set -e
  yamllint roles
  ansible-lint roles
  flake8 plugins

driver:
  name: docker

platforms:
  - name: ubuntu-focal
    image: library/ubuntu:20.04
    pre_build_image: false
  - name: ubuntu-jammy
    image: library/ubuntu:22.04
    pre_build_image: false

provisioner:
  name: ansible
verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
