---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: vision-focal
    image: ubuntu:20.04
    pre_build_image: false
  - name: vision-jammy
    image: ubuntu:22.04
    pre_build_image: false

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      stderr_callback: yaml

scenario:
  name: vision_tools
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
