---
- name: Gather information on gradle installation
  ansible.builtin.stat:
    path: "{{ test_wpilib_home }}/.gradle/{{ item }}/dists/gradle-{{ test_gradle.version }}-bin/{{ test_gradle.hash }}"
  loop:
    - wrapper
    - permwrapper
  register: directories

- name: Assert gradle installation is created
  ansible.builtin.assert:
    that:
      - wrapper_dir.stat.exists
      - wrapper_dir.stat.isdir
      - wrapper_dir.stat.mode == test_wpilib_mode
      - wrapper_dir.stat.pw_name == test_wpilib_user
      - wrapper_dir.stat.gr_name == test_wpilib_group
  loop: "{{ directories.results }}"
  loop_control:
    loop_var: wrapper_dir
