- name: Gather information on app shortcut
  ansible.builtin.stat:
    path: "{{ test_wpilib_home }}/.local/share/applications/{{ item }}"
  register: test_shortcut_stats
  loop: "{{ test_shortcut.list }}"

- name: Assert app shortcut properties
  ansible.builtin.assert:
    that:
      - desktop_shortcut_file.stat.exists
      - desktop_shortcut_file.stat.mode == test_shortcut.mode
  loop: "{{ test_shortcut_stats.results }}"
  loop_control:
    loop_var: desktop_shortcut_file

- name: Check shortcut metadata
  ansible.builtin.shell:
    cmd: "dbus-launch gio info {{ desktop_shortcut_file.stat.path }} | grep metadata::trusted | xargs echo | cut -d ' ' -f 2"
  register: shortcuts_trusted
  changed_when: false
  become: true
  become_user: "{{ test_wpilib_user }}"
  loop: "{{ test_shortcut_stats.results }}"
  loop_control:
    loop_var: desktop_shortcut_file

- name: Assert app shortcut is trusted
  ansible.builtin.assert:
    that:
      - shortcut_trusted.stdout == "true"
  loop: "{{ shortcuts_trusted.results }}"
  loop_control:
    loop_var: shortcut_trusted