---
- name: Install role dependencies
  ansible.builtin.package:
    name:
      - gzip
      - jq
      - python3
      - tar
    state: present
    use: apt
  become: true

- name: Install vscode
  include_role:
    name: gantsign.visual-studio-code
  when: ansible_distribution != 'Pop!_OS'

- name: Install vscode (Pop! OS)
  ansible.builtin.package:
    name:
      - code
    use: apt
  when: ansible_distribution == 'Pop!_OS'
  become: true

- name: Install dev tools
  ansible.builtin.package:
    name:
      - git
      - neovim
      - tree
  become: true

- name: Create wpilib global install root
  ansible.builtin.file:
    dest: "{{ wpilib_install_root }}"
    state: directory
    recurse: true
  become: true

- name: Download wpilib release
  ansible.builtin.get_url:
    url: "{{ wpilib_url }}/{{ wpilib_archive }}"
    dest: "{{ wpilib_install_root }}/{{ wpilib_archive }}"
    checksum: "{{ wpilib_release_hash }}"
  become: true

- name: Unpack release
  ansible.builtin.unarchive:
    src: "{{ wpilib_install_root }}/{{ wpilib_archive }}"
    dest: "{{ wpilib_install_root }}"
    include: "{{ wpilib_artifacts_archive }}"
    creates: "{{ wpilib_install_root }}/{{ wpilib_artifacts_archive }}"
    remote_src: true
  become: true

- name: Install wpilib for each user
  include_tasks: user-install.yml
  loop: "{{ wpilib_users }}"
  loop_control:
    loop_var: user
